/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampagnesIndexRouteImport } from './routes/campagnes.index'
import { Route as CampagnesIdRouteImport } from './routes/campagnes.$id'
import { Route as CampagnesNouvelleRouteImport } from './routes/campagnes.nouvelle'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueIdRouteImport } from './routes/catalogue.$id'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as CommandesIndexRouteImport } from './routes/commandes.index'
import { Route as CommandesIdRouteImport } from './routes/commandes.$id'
import { Route as DevisIndexRouteImport } from './routes/devis.index'
import { Route as DevisIdRouteImport } from './routes/devis.$id'
import { Route as DevisNouveauRouteImport } from './routes/devis.nouveau'
import { Route as FacturesIndexRouteImport } from './routes/factures.index'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as OpportunitesIndexRouteImport } from './routes/opportunites.index'
import { Route as PaiementsIndexRouteImport } from './routes/paiements.index'
import { Route as PaiementsIdRouteImport } from './routes/paiements.$id'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'
import { Route as VentesIndexRouteImport } from './routes/ventes.index'
import { Route as VentesIdRouteImport } from './routes/ventes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesIndexRoute = CampagnesIndexRouteImport.update({
  id: '/campagnes/',
  path: '/campagnes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesIdRoute = CampagnesIdRouteImport.update({
  id: '/campagnes/$id',
  path: '/campagnes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesNouvelleRoute = CampagnesNouvelleRouteImport.update({
  id: '/campagnes/nouvelle',
  path: '/campagnes/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIdRoute = CatalogueIdRouteImport.update({
  id: '/catalogue/$id',
  path: '/catalogue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIndexRoute = CommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIdRoute = CommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisIndexRoute = DevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisIdRoute = DevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisNouveauRoute = DevisNouveauRouteImport.update({
  id: '/devis/nouveau',
  path: '/devis/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIndexRoute = FacturesIndexRouteImport.update({
  id: '/factures/',
  path: '/factures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesIndexRoute = OpportunitesIndexRouteImport.update({
  id: '/opportunites/',
  path: '/opportunites/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsIndexRoute = PaiementsIndexRouteImport.update({
  id: '/paiements/',
  path: '/paiements/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsIdRoute = PaiementsIdRouteImport.update({
  id: '/paiements/$id',
  path: '/paiements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesIndexRoute = VentesIndexRouteImport.update({
  id: '/ventes/',
  path: '/ventes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesIdRoute = VentesIdRouteImport.update({
  id: '/ventes/$id',
  path: '/ventes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/devis/$id': typeof DevisIdRoute
  '/devis/nouveau': typeof DevisNouveauRoute
  '/factures/$id': typeof FacturesIdRoute
  '/locations/$id': typeof LocationsIdRoute
  '/paiements/$id': typeof PaiementsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/ventes/$id': typeof VentesIdRoute
  '/campagnes/': typeof CampagnesIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/commandes/': typeof CommandesIndexRoute
  '/devis/': typeof DevisIndexRoute
  '/factures/': typeof FacturesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/opportunites/': typeof OpportunitesIndexRoute
  '/paiements/': typeof PaiementsIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
  '/ventes/': typeof VentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/devis/$id': typeof DevisIdRoute
  '/devis/nouveau': typeof DevisNouveauRoute
  '/factures/$id': typeof FacturesIdRoute
  '/locations/$id': typeof LocationsIdRoute
  '/paiements/$id': typeof PaiementsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/ventes/$id': typeof VentesIdRoute
  '/campagnes': typeof CampagnesIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/commandes': typeof CommandesIndexRoute
  '/devis': typeof DevisIndexRoute
  '/factures': typeof FacturesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/opportunites': typeof OpportunitesIndexRoute
  '/paiements': typeof PaiementsIndexRoute
  '/prospects': typeof ProspectsIndexRoute
  '/ventes': typeof VentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/catalogue/$id': typeof CatalogueIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/devis/$id': typeof DevisIdRoute
  '/devis/nouveau': typeof DevisNouveauRoute
  '/factures/$id': typeof FacturesIdRoute
  '/locations/$id': typeof LocationsIdRoute
  '/paiements/$id': typeof PaiementsIdRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/ventes/$id': typeof VentesIdRoute
  '/campagnes/': typeof CampagnesIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/commandes/': typeof CommandesIndexRoute
  '/devis/': typeof DevisIndexRoute
  '/factures/': typeof FacturesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/opportunites/': typeof OpportunitesIndexRoute
  '/paiements/': typeof PaiementsIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
  '/ventes/': typeof VentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/catalogue/$id'
    | '/clients/$id'
    | '/commandes/$id'
    | '/devis/$id'
    | '/devis/nouveau'
    | '/factures/$id'
    | '/locations/$id'
    | '/paiements/$id'
    | '/prospects/$id'
    | '/ventes/$id'
    | '/campagnes/'
    | '/catalogue/'
    | '/clients/'
    | '/commandes/'
    | '/devis/'
    | '/factures/'
    | '/locations/'
    | '/opportunites/'
    | '/paiements/'
    | '/prospects/'
    | '/ventes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/catalogue/$id'
    | '/clients/$id'
    | '/commandes/$id'
    | '/devis/$id'
    | '/devis/nouveau'
    | '/factures/$id'
    | '/locations/$id'
    | '/paiements/$id'
    | '/prospects/$id'
    | '/ventes/$id'
    | '/campagnes'
    | '/catalogue'
    | '/clients'
    | '/commandes'
    | '/devis'
    | '/factures'
    | '/locations'
    | '/opportunites'
    | '/paiements'
    | '/prospects'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/catalogue/$id'
    | '/clients/$id'
    | '/commandes/$id'
    | '/devis/$id'
    | '/devis/nouveau'
    | '/factures/$id'
    | '/locations/$id'
    | '/paiements/$id'
    | '/prospects/$id'
    | '/ventes/$id'
    | '/campagnes/'
    | '/catalogue/'
    | '/clients/'
    | '/commandes/'
    | '/devis/'
    | '/factures/'
    | '/locations/'
    | '/opportunites/'
    | '/paiements/'
    | '/prospects/'
    | '/ventes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampagnesIdRoute: typeof CampagnesIdRoute
  CampagnesNouvelleRoute: typeof CampagnesNouvelleRoute
  CatalogueIdRoute: typeof CatalogueIdRoute
  ClientsIdRoute: typeof ClientsIdRoute
  CommandesIdRoute: typeof CommandesIdRoute
  DevisIdRoute: typeof DevisIdRoute
  DevisNouveauRoute: typeof DevisNouveauRoute
  FacturesIdRoute: typeof FacturesIdRoute
  LocationsIdRoute: typeof LocationsIdRoute
  PaiementsIdRoute: typeof PaiementsIdRoute
  ProspectsIdRoute: typeof ProspectsIdRoute
  VentesIdRoute: typeof VentesIdRoute
  CampagnesIndexRoute: typeof CampagnesIndexRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  CommandesIndexRoute: typeof CommandesIndexRoute
  DevisIndexRoute: typeof DevisIndexRoute
  FacturesIndexRoute: typeof FacturesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  OpportunitesIndexRoute: typeof OpportunitesIndexRoute
  PaiementsIndexRoute: typeof PaiementsIndexRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
  VentesIndexRoute: typeof VentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/': {
      id: '/campagnes/'
      path: '/campagnes'
      fullPath: '/campagnes/'
      preLoaderRoute: typeof CampagnesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/$id': {
      id: '/campagnes/$id'
      path: '/campagnes/$id'
      fullPath: '/campagnes/$id'
      preLoaderRoute: typeof CampagnesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/nouvelle': {
      id: '/campagnes/nouvelle'
      path: '/campagnes/nouvelle'
      fullPath: '/campagnes/nouvelle'
      preLoaderRoute: typeof CampagnesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$id': {
      id: '/catalogue/$id'
      path: '/catalogue/$id'
      fullPath: '/catalogue/$id'
      preLoaderRoute: typeof CatalogueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/': {
      id: '/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof CommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/$id': {
      id: '/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof CommandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/': {
      id: '/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof DevisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/$id': {
      id: '/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof DevisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis/nouveau': {
      id: '/devis/nouveau'
      path: '/devis/nouveau'
      fullPath: '/devis/nouveau'
      preLoaderRoute: typeof DevisNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/': {
      id: '/factures/'
      path: '/factures'
      fullPath: '/factures/'
      preLoaderRoute: typeof FacturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites/': {
      id: '/opportunites/'
      path: '/opportunites'
      fullPath: '/opportunites/'
      preLoaderRoute: typeof OpportunitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements/': {
      id: '/paiements/'
      path: '/paiements'
      fullPath: '/paiements/'
      preLoaderRoute: typeof PaiementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements/$id': {
      id: '/paiements/$id'
      path: '/paiements/$id'
      fullPath: '/paiements/$id'
      preLoaderRoute: typeof PaiementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes/': {
      id: '/ventes/'
      path: '/ventes'
      fullPath: '/ventes/'
      preLoaderRoute: typeof VentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes/$id': {
      id: '/ventes/$id'
      path: '/ventes/$id'
      fullPath: '/ventes/$id'
      preLoaderRoute: typeof VentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampagnesIdRoute: CampagnesIdRoute,
  CampagnesNouvelleRoute: CampagnesNouvelleRoute,
  CatalogueIdRoute: CatalogueIdRoute,
  ClientsIdRoute: ClientsIdRoute,
  CommandesIdRoute: CommandesIdRoute,
  DevisIdRoute: DevisIdRoute,
  DevisNouveauRoute: DevisNouveauRoute,
  FacturesIdRoute: FacturesIdRoute,
  LocationsIdRoute: LocationsIdRoute,
  PaiementsIdRoute: PaiementsIdRoute,
  ProspectsIdRoute: ProspectsIdRoute,
  VentesIdRoute: VentesIdRoute,
  CampagnesIndexRoute: CampagnesIndexRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  CommandesIndexRoute: CommandesIndexRoute,
  DevisIndexRoute: DevisIndexRoute,
  FacturesIndexRoute: FacturesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  OpportunitesIndexRoute: OpportunitesIndexRoute,
  PaiementsIndexRoute: PaiementsIndexRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
  VentesIndexRoute: VentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
