/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampagnesIndexRouteImport } from './routes/campagnes.index'
import { Route as CampagnesIdRouteImport } from './routes/campagnes.$id'
import { Route as CampagnesNouvelleRouteImport } from './routes/campagnes.nouvelle'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesIndexRoute = CampagnesIndexRouteImport.update({
  id: '/campagnes/',
  path: '/campagnes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesIdRoute = CampagnesIdRouteImport.update({
  id: '/campagnes/$id',
  path: '/campagnes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampagnesNouvelleRoute = CampagnesNouvelleRouteImport.update({
  id: '/campagnes/nouvelle',
  path: '/campagnes/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/campagnes/': typeof CampagnesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/campagnes': typeof CampagnesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campagnes/$id': typeof CampagnesIdRoute
  '/campagnes/nouvelle': typeof CampagnesNouvelleRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/campagnes/': typeof CampagnesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/prospects/$id'
    | '/campagnes/'
    | '/clients/'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/prospects/$id'
    | '/campagnes'
    | '/clients'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/campagnes/$id'
    | '/campagnes/nouvelle'
    | '/prospects/$id'
    | '/campagnes/'
    | '/clients/'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampagnesIdRoute: typeof CampagnesIdRoute
  CampagnesNouvelleRoute: typeof CampagnesNouvelleRoute
  ProspectsIdRoute: typeof ProspectsIdRoute
  CampagnesIndexRoute: typeof CampagnesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/': {
      id: '/campagnes/'
      path: '/campagnes'
      fullPath: '/campagnes/'
      preLoaderRoute: typeof CampagnesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/$id': {
      id: '/campagnes/$id'
      path: '/campagnes/$id'
      fullPath: '/campagnes/$id'
      preLoaderRoute: typeof CampagnesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campagnes/nouvelle': {
      id: '/campagnes/nouvelle'
      path: '/campagnes/nouvelle'
      fullPath: '/campagnes/nouvelle'
      preLoaderRoute: typeof CampagnesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampagnesIdRoute: CampagnesIdRoute,
  CampagnesNouvelleRoute: CampagnesNouvelleRoute,
  ProspectsIdRoute: ProspectsIdRoute,
  CampagnesIndexRoute: CampagnesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
